config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :congressional_members
  resources :congressional_chambers
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/congressional_chamber.rb
class CongressionalChamber < ApplicationRecord
    # relation with the congress
    has_many :congressional_terms
    has_many :congresses, through: :congressional_terms

    # relation with the congressional_members
    has_many :terms
    has_many :congressional_members, through: :terms
end

app/controllers/congressional_chambers_controller.rb
class CongressionalChambersController < ApplicationController
  before_action :set_congressional_chamber, only: [:show, :edit, :update, :destroy]

  # GET /congressional_chambers
  # GET /congressional_chambers.json
  def index
    @congressional_chambers = CongressionalChamber.all
  end

  # GET /congressional_chambers/1
  # GET /congressional_chambers/1.json
  def show
  end

  # GET /congressional_chambers/new
  def new
    @congressional_chamber = CongressionalChamber.new
  end

  # GET /congressional_chambers/1/edit
  def edit
  end

  # POST /congressional_chambers
  # POST /congressional_chambers.json
  def create
    @congressional_chamber = CongressionalChamber.new(congressional_chamber_params)

    respond_to do |format|
      if @congressional_chamber.save
        format.html { redirect_to @congressional_chamber, notice: 'Congressional chamber was successfully created.' }
        format.json { render :show, status: :created, location: @congressional_chamber }
      else
        format.html { render :new }
        format.json { render json: @congressional_chamber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /congressional_chambers/1
  # PATCH/PUT /congressional_chambers/1.json
  def update
    respond_to do |format|
      if @congressional_chamber.update(congressional_chamber_params)
        format.html { redirect_to @congressional_chamber, notice: 'Congressional chamber was successfully updated.' }
        format.json { render :show, status: :ok, location: @congressional_chamber }
      else
        format.html { render :edit }
        format.json { render json: @congressional_chamber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congressional_chambers/1
  # DELETE /congressional_chambers/1.json
  def destroy
    @congressional_chamber.destroy
    respond_to do |format|
      format.html { redirect_to congressional_chambers_url, notice: 'Congressional chamber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_congressional_chamber
      @congressional_chamber = CongressionalChamber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def congressional_chamber_params
      params.require(:congressional_chamber).permit(:name)
    end
end

app/helpers/congressional_chambers_helper.rb
module CongressionalChambersHelper
end

app/views/congressional_chambers/_form.html.erb
<%= form_with(model: congressional_chamber, local: true) do |form| %>
  <% if congressional_chamber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(congressional_chamber.errors.count, "error") %> prohibited this congressional_chamber from being saved:</h2>

      <ul>
      <% congressional_chamber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if congressional_chamber.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', congressional_chamber, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if congressional_chamber.persisted? %>
      <%= link_to "Cancel", congressional_chamber, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", congressional_chambers_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/congressional_chambers/edit.html.erb
<h1>Edit Congressional_chamber</h1>

<%= render 'form', congressional_chamber: @congressional_chamber %>

app/views/congressional_chambers/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Congressional_chambers</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_congressional_chamber_path, class: 'btn btn-primary' do %>
    Add New Congressional chamber
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            
      </tr>
    </thead>

    <tbody>
      <% @congressional_chambers.each do |congressional_chamber| %>
        <%= content_tag :tr, id: dom_id(congressional_chamber), class: dom_class(congressional_chamber) do %>
          
            <td><%= link_to congressional_chamber.name, congressional_chamber %></td>
          

          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/congressional_chambers/new.html.erb
<h1>New congressional_chamber</h1>

<%= render 'form', congressional_chamber: @congressional_chamber %>

app/views/congressional_chambers/show.html.erb
<div class="page-header">
  <%= link_to congressional_chambers_path, class: 'btn btn-default' do %>
    All Congressional_chambers
  <% end %>
  <%= link_to edit_congressional_chamber_path(@congressional_chamber), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show congressional_chamber</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @congressional_chamber.name %></dd>

</dl>