config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :congressional_members
  resources :congressional_chambers
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/congressional_member.rb
class CongressionalMember < ApplicationRecord
    has_many :terms
    has_many :congresses, through: :terms

    def self.create_or_update_member(member_data) #in an OpenStruct
        @congressional_member = CongressionalMember.find_or_create_by(bio_directory_id: member_data.bio_directory_id)
        @congressional_member.update(first_name: member_data.first_name,
            middle_name:        member_data.middle_name,
            last_name:          member_data.last_name,
            suffix:             member_data.suffix,
            title:              member_data.title,
            short_title:        member_data.short_title,
            date_of_birth:      member_data.date_of_birth,
            gender:             member_data.gender,
            party:              member_data.party,
            leadership_role:    member_data.leadership_role,
            twitter_account:    member_data.twitter_account,
            facebook_account:   member_data.facebook_account,
            youtube_account:    member_data.youtube_account,
            govtrack_id:        member_data.govtrack_id,
            cspan_id:           member_data.cspan_id,
            votesmart_id:       member_data.votesmart_id,
            icpsr_id:           member_data.icpsr_id,
            crp_id:             member_data.crp_id,
            google_entity_id:   member_data.google_entity_id,
            fec_candidate_id:   member_data.fec_candidate_id,
            url:                member_data.url,
            rss_url:            member_data.rss_url,
            contact_form:       member_data.contact_form,
            in_office:          member_data.in_office,
            cook_pvi:           member_data.cook_pvi
        )
        @congressional_member
    end

end

app/controllers/congressional_members_controller.rb
class CongressionalMembersController < ApplicationController
  before_action :set_congressional_member, only: [:show, :edit, :update, :destroy]

  # GET /congressional_members
  # GET /congressional_members.json
  def index
    @congressional_members = CongressionalMember.first(25)
  end

  # GET /congressional_members/1
  # GET /congressional_members/1.json
  def show
  end

  # GET /congressional_members/new
  def new
    @congressional_member = CongressionalMember.new
  end

  # GET /congressional_members/1/edit
  def edit
  end

  # POST /congressional_members
  # POST /congressional_members.json
  def create
    @congressional_member = CongressionalMember.new(congressional_member_params)

    respond_to do |format|
      if @congressional_member.save
        format.html { redirect_to @congressional_member, notice: 'Congressional member was successfully created.' }
        format.json { render :show, status: :created, location: @congressional_member }
      else
        format.html { render :new }
        format.json { render json: @congressional_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /congressional_members/1
  # PATCH/PUT /congressional_members/1.json
  def update
    respond_to do |format|
      if @congressional_member.update(congressional_member_params)
        format.html { redirect_to @congressional_member, notice: 'Congressional member was successfully updated.' }
        format.json { render :show, status: :ok, location: @congressional_member }
      else
        format.html { render :edit }
        format.json { render json: @congressional_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congressional_members/1
  # DELETE /congressional_members/1.json
  def destroy
    @congressional_member.destroy
    respond_to do |format|
      format.html { redirect_to congressional_members_url, notice: 'Congressional member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_congressional_member
      @congressional_member = CongressionalMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def congressional_member_params
      params.require(:congressional_member).permit(:title, :short_title, :bio_directory_id, :first_name, :middle_name, :last_name, :suffix, :date_of_birth, :gender, :party, :leadership_role, :twitter_account, :facebook_account, :youtube_account, :govtrack_id, :cspan_id, :votesmart_id, :icpsr_id, :crp_id, :google_entity_id, :fec_candidate_id, :url, :rss_url, :contact_form, :in_office, :cook_pvi, :dw_nominate, :ideal_point, :seniority, :next_election, :total_votes, :missed_votes, :total_present, :ocd_id, :office, :phone, :fax, :state, :senate_class, :state_rank, :lis_id, :missed_votes_pct, :votes_with_party_pct, :votes_against_party_pct)
    end
end

app/helpers/congressional_members_helper.rb
module CongressionalMembersHelper
end

app/views/congressional_members/_form.html.erb
<%= form_with(model: congressional_member, local: true) do |form| %>
  <% if congressional_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(congressional_member.errors.count, "error") %> prohibited this congressional_member from being saved:</h2>

      <ul>
      <% congressional_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :short_title %>
    <%= form.text_field :short_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :bio_directory_id %>
    <%= form.text_field :bio_directory_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :suffix %>
    <%= form.text_field :suffix, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :party %>
    <%= form.text_field :party, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :leadership_role %>
    <%= form.text_field :leadership_role, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :twitter_account %>
    <%= form.text_field :twitter_account, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :facebook_account %>
    <%= form.text_field :facebook_account, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :youtube_account %>
    <%= form.text_field :youtube_account, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :govtrack_id %>
    <%= form.text_field :govtrack_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cspan_id %>
    <%= form.text_field :cspan_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :votesmart_id %>
    <%= form.text_field :votesmart_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :icpsr_id %>
    <%= form.text_field :icpsr_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :crp_id %>
    <%= form.text_field :crp_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :google_entity_id %>
    <%= form.text_field :google_entity_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :fec_candidate_id %>
    <%= form.text_field :fec_candidate_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rss_url %>
    <%= form.text_field :rss_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :contact_form %>
    <%= form.text_field :contact_form, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :in_office %>
    <%= form.text_field :in_office, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cook_pvi %>
    <%= form.text_field :cook_pvi, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :dw_nominate %>
    <%= form.text_field :dw_nominate, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :ideal_point %>
    <%= form.text_field :ideal_point, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :seniority %>
    <%= form.text_field :seniority, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :next_election %>
    <%= form.text_field :next_election, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :total_votes %>
    <%= form.text_field :total_votes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :missed_votes %>
    <%= form.text_field :missed_votes, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :total_present %>
    <%= form.text_field :total_present, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :ocd_id %>
    <%= form.text_field :ocd_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :office %>
    <%= form.text_field :office, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :fax %>
    <%= form.text_field :fax, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :senate_class %>
    <%= form.text_field :senate_class, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :state_rank %>
    <%= form.text_field :state_rank, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :lis_id %>
    <%= form.text_field :lis_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :missed_votes_pct %>
    <%= form.text_field :missed_votes_pct, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :votes_with_party_pct %>
    <%= form.text_field :votes_with_party_pct, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :votes_against_party_pct %>
    <%= form.text_field :votes_against_party_pct, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if congressional_member.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', congressional_member, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if congressional_member.persisted? %>
      <%= link_to "Cancel", congressional_member, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", congressional_members_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/congressional_members/_member_hexagon.html.erb
	<div class="block">
  <%=link_to member do %>
      <img src="https://theunitedstates.io/images/congress/225x275/<%= member.bio_directory_id %>.jpg" alt="<%= member.short_title %><%= member.first_name %><%= member.last_name %>" class="headshot">
  <% end %>

  </div>  
 

app/views/congressional_members/edit.html.erb
<h1>Edit Congressional_member</h1>

<%= render 'form', congressional_member: @congressional_member %>

app/views/congressional_members/index.html.erb
<%# start hive grid %>

<header><h1>Hive looking responsive grid</h1>
	<p>Change <span>$block-size</span> value in the CSS and <span>resize the window</span> to see it in action</p>
</header>
	<div class="grid">
  <%= render partial: "member_hexagon", collection: @congressional_members, as: :member %>

	</div>

<div class="row">
  <div class="col-sm-6">
    <h1>Congressional_members</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_congressional_member_path, class: 'btn btn-primary' do %>
    Add New Congressional member
  <% end %>
  </div>
</div>

app/views/congressional_members/new.html.erb
<h1>New congressional_member</h1>

<%= render 'form', congressional_member: @congressional_member %>

app/views/congressional_members/show.html.erb
<div class="page-header">
  <%= link_to congressional_members_path, class: 'btn btn-default' do %>
    All Congressional_members
  <% end %>
  <%= link_to edit_congressional_member_path(@congressional_member), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show congressional_member</h1>
</div>

<dl class="dl-horizontal">
  <dt>Headshot:</dt>
  <dd><img class="headshot" 
      src='https://theunitedstates.io/images/congress/225x275/<%= @congressional_member.bio_directory_id %>.jpg' 
      alt="headshot"  
      width="250" 
      height="275" />
  </dd>
  <dt>Title:</dt>
  <dd><%= @congressional_member.title %></dd>

  <dt>Short title:</dt>
  <dd><%= @congressional_member.short_title %></dd>

  <dt>Bio directory:</dt>
  <dd><%= @congressional_member.bio_directory_id %></dd>

  <dt>First name:</dt>
  <dd><%= @congressional_member.first_name %></dd>

  <dt>Middle name:</dt>
  <dd><%= @congressional_member.middle_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @congressional_member.last_name %></dd>

  <dt>Suffix:</dt>
  <dd><%= @congressional_member.suffix %></dd>

  <dt>Date of birth:</dt>
  <dd><%= @congressional_member.date_of_birth %></dd>

  <dt>Gender:</dt>
  <dd><%= @congressional_member.gender %></dd>

  <dt>Party:</dt>
  <dd><%= @congressional_member.party %></dd>

  <dt>Leadership role:</dt>
  <dd><%= @congressional_member.leadership_role %></dd>

  <dt>Twitter account:</dt>
  <dd><%= @congressional_member.twitter_account %></dd>

  <dt>Facebook account:</dt>
  <dd><%= @congressional_member.facebook_account %></dd>

  <dt>Youtube account:</dt>
  <dd><%= @congressional_member.youtube_account %></dd>

  <dt>Govtrack:</dt>
  <dd><%= @congressional_member.govtrack_id %></dd>

  <dt>Cspan:</dt>
  <dd><%= @congressional_member.cspan_id %></dd>

  <dt>Votesmart:</dt>
  <dd><%= @congressional_member.votesmart_id %></dd>

  <dt>Icpsr:</dt>
  <dd><%= @congressional_member.icpsr_id %></dd>

  <dt>Crp:</dt>
  <dd><%= @congressional_member.crp_id %></dd>

  <dt>Google entity:</dt>
  <dd><%= @congressional_member.google_entity_id %></dd>

  <dt>Fec candidate:</dt>
  <dd><%= @congressional_member.fec_candidate_id %></dd>

  <dt>Url:</dt>
  <dd><%= @congressional_member.url %></dd>

  <dt>Rss url:</dt>
  <dd><%= @congressional_member.rss_url %></dd>

  <dt>Contact form:</dt>
  <dd><%= @congressional_member.contact_form %></dd>

  <dt>In office:</dt>
  <dd><%= @congressional_member.in_office %></dd>

  <dt>Cook pvi:</dt>
  <dd><%= @congressional_member.cook_pvi %></dd>

  <dt>Dw nominate:</dt>
  <dd><%= @congressional_member.dw_nominate %></dd>

  <dt>Ideal point:</dt>
  <dd><%= @congressional_member.ideal_point %></dd>

  <dt>Seniority:</dt>
  <dd><%= @congressional_member.seniority %></dd>

  <dt>Next election:</dt>
  <dd><%= @congressional_member.next_election %></dd>

  <dt>Total votes:</dt>
  <dd><%= @congressional_member.total_votes %></dd>

  <dt>Missed votes:</dt>
  <dd><%= @congressional_member.missed_votes %></dd>

  <dt>Total present:</dt>
  <dd><%= @congressional_member.total_present %></dd>

  <dt>Ocd:</dt>
  <dd><%= @congressional_member.ocd_id %></dd>

  <dt>Office:</dt>
  <dd><%= @congressional_member.office %></dd>

  <dt>Phone:</dt>
  <dd><%= @congressional_member.phone %></dd>

  <dt>Fax:</dt>
  <dd><%= @congressional_member.fax %></dd>

  <dt>State:</dt>
  <dd><%= @congressional_member.state %></dd>

  <dt>Senate class:</dt>
  <dd><%= @congressional_member.senate_class %></dd>

  <dt>State rank:</dt>
  <dd><%= @congressional_member.state_rank %></dd>

  <dt>Lis:</dt>
  <dd><%= @congressional_member.lis_id %></dd>

  <dt>Missed votes pct:</dt>
  <dd><%= @congressional_member.missed_votes_pct %></dd>

  <dt>Votes with party pct:</dt>
  <dd><%= @congressional_member.votes_with_party_pct %></dd>

  <dt>Votes against party pct:</dt>
  <dd><%= @congressional_member.votes_against_party_pct %></dd>

</dl>

app/views/congressional_members/user_svg.html.erb
<span data-balloon="size: 5x" data-balloon-pos="up" class="db color-inherit link hover-lime">
    <%# svg from fontawesome https://fontawesome.com/icons/user?style=solid %>
    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="svg-inline--fa fa-user fa-w-14 fa-5x"><path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z" class=""></path></svg>
</span>